# Generated by Django 5.1.4 on 2024-12-11 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponser',
            name='contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='discription',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
