# Generated by Django 5.1.4 on 2024-12-12 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_sponser_contact_alter_study_discription'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='attachment',
            field=models.FileField(null=True, upload_to='study_attachment'),
        ),
    ]
