# Generated by Django 5.1.4 on 2024-12-12 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_study_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='attachment',
            field=models.FileField(null=True, upload_to='study_attachment'),
        ),
    ]
